# Generated by Django 2.2.7 on 2019-11-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupType', models.CharField(max_length=15, verbose_name='Группа пользователя')),
                ('Active', models.BooleanField(help_text='Активена / Не активена', verbose_name='Статус группы')),
            ],
            options={
                'verbose_name_plural': 'Пользовательские группы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=30, verbose_name='Логин пользователя')),
                ('FirstName', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('LastName', models.CharField(max_length=30, verbose_name='Фамилия пользователя')),
                ('Gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол пользователя')),
                ('Phone', models.CharField(max_length=30, verbose_name='Мобильный телефон пользователя')),
                ('Email', models.CharField(max_length=30, unique=True, verbose_name='Емейл пользователя')),
                ('Password', models.CharField(default='None', max_length=30, verbose_name='Пароль пользователя')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, help_text='День, когда был создан аккаунт', verbose_name='Дата создания')),
                ('ModifiedDate', models.DateTimeField(auto_now_add=True, help_text='Когда было изменено что-нибудь в аккаунте', verbose_name='Дата последнего изменения')),
                ('Active', models.BooleanField(default=True, help_text='Активен / Не активен', verbose_name='Статус пользователя')),
                ('GroupID', models.ForeignKey(help_text='К какой группе относится пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to='motor.UserGroup', verbose_name='Группа пользователя')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
