# Generated by Django 2.2.7 on 2020-01-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameCar', models.CharField(max_length=55, verbose_name='Марка автомобиля')),
                ('SeriaCar', models.CharField(max_length=55, verbose_name='Серия автомобиля')),
                ('YearCar', models.CharField(max_length=55, verbose_name='Год выпуска автомобиля')),
                ('KuzovCar', models.CharField(max_length=55, verbose_name='Кузов автомобиля')),
                ('GenerationCar', models.CharField(max_length=55, verbose_name='Поколение автомобиля')),
                ('GearCar', models.CharField(max_length=55, verbose_name='Коробка автомобиля')),
                ('DriveCar', models.CharField(max_length=55, verbose_name='Привод автомобиля')),
                ('MotorCar', models.CharField(max_length=55, verbose_name='Двигатель автомобиля')),
                ('ModificationCar', models.CharField(max_length=55, verbose_name='Модификация автомобиля')),
                ('ColorCar', models.CharField(max_length=55, verbose_name='Название автомобиля')),
                ('ImageCar', models.ImageField(upload_to='cars/')),
                ('MediaCar', models.CharField(max_length=55, verbose_name='Мультмедиа автомобиля')),
                ('MediaSystemCar', models.CharField(max_length=55, verbose_name='Мультмедиасистемы автомобиля')),
                ('MediaAudioSystemCar', models.CharField(max_length=55, verbose_name='Мультмедиааудиосистемы автомобиля')),
                ('ComfortCar1', models.CharField(max_length=55, verbose_name='Комфорт1 автомобиля')),
                ('ComfortCar2', models.CharField(max_length=55, verbose_name='Комфорт2 автомобиля')),
                ('ComfortCar3', models.CharField(max_length=55, verbose_name='Комфорт3 автомобиля')),
                ('SecurityCar1', models.CharField(max_length=55, verbose_name='Безопасность1 автомобиля')),
                ('SecurityCar2', models.CharField(max_length=55, verbose_name='Безопасность2 автомобиля')),
                ('SecurityCar3', models.CharField(max_length=55, verbose_name='Безопасность3 автомобиля')),
                ('BuyYearCar', models.CharField(max_length=55, verbose_name='Год покупки автомобиля')),
                ('BuyMonthCar', models.CharField(max_length=55, verbose_name='Месяц покупки автомобиля')),
                ('RunCar', models.CharField(max_length=55, verbose_name='Пробег автомобиля')),
                ('PriceCar', models.CharField(max_length=55, verbose_name='Цена автомобиля')),
                ('OwnerCar', models.CharField(max_length=55, verbose_name='Владелец автомобиля')),
                ('DopCar', models.CharField(max_length=55, verbose_name='Дополнительное описание автомобиля')),
                ('YourName', models.CharField(max_length=55, verbose_name='Ваше имя')),
                ('YourPhone', models.CharField(max_length=55, verbose_name='Ваш телефон')),
                ('YourMail', models.CharField(max_length=55, verbose_name='Ваша почта')),
                ('YourCity', models.CharField(max_length=55, verbose_name='Город продажи')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor.User')),
            ],
            options={
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
