# Generated by Django 2.2.7 on 2020-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_advertisecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisecar',
            name='YourCity',
            field=models.CharField(default='None', max_length=25, verbose_name='Город продажи'),
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='YourMail',
            field=models.CharField(default='None', max_length=25, unique=True, verbose_name='Ваша почта'),
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='YourName',
            field=models.CharField(default='None', max_length=25, verbose_name='Ваше имя'),
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='YourPhone',
            field=models.CharField(default='None', max_length=25, verbose_name='Ваш телефон'),
        ),
    ]
