# Generated by Django 2.2.7 on 2020-01-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_auto_20200110_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisecar',
            name='YourMail',
            field=models.CharField(default='None', max_length=25, verbose_name='Ваша почта'),
        ),
    ]
