# Generated by Django 2.2.7 on 2020-01-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0004_advertisecomments_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisecomments',
            name='ID_User',
        ),
    ]
