# Generated by Django 2.2.7 on 2020-01-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0004_auto_20200111_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisecar',
            name='YourCity',
            field=models.CharField(max_length=25, verbose_name='Город продажи'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='YourMail',
            field=models.CharField(max_length=25, verbose_name='Ваша почта'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='YourName',
            field=models.CharField(max_length=25, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='YourPhone',
            field=models.CharField(max_length=25, verbose_name='Ваш телефон'),
        ),
    ]
