# Generated by Django 2.2.7 on 2020-01-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0005_auto_20200111_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisecar',
            name='BuyMonthCar',
            field=models.CharField(max_length=55, verbose_name='Месяц покупки автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='BuyYearCar',
            field=models.CharField(max_length=55, verbose_name='Год покупки автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='ColorCar',
            field=models.CharField(max_length=55, verbose_name='Название автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='ComfortCar',
            field=models.CharField(max_length=55, verbose_name='Комфорт автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='DopCar',
            field=models.CharField(max_length=55, verbose_name='Дополнительное описание автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='DriveCar',
            field=models.CharField(max_length=55, verbose_name='Привод автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='GearCar',
            field=models.CharField(max_length=55, verbose_name='Коробка автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='GenerationCar',
            field=models.CharField(max_length=55, verbose_name='Поколение автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='KuzovCar',
            field=models.CharField(max_length=55, verbose_name='Кузов автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='MediaCar',
            field=models.CharField(max_length=55, verbose_name='Мультмедиа автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='ModificationCar',
            field=models.CharField(max_length=55, verbose_name='Модификация автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='MotorCar',
            field=models.CharField(max_length=55, verbose_name='Двигатель автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='NameCar',
            field=models.CharField(max_length=55, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='OwnerCar',
            field=models.CharField(max_length=55, verbose_name='Владелец автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='PriceCar',
            field=models.CharField(max_length=55, verbose_name='Цена автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='RunCar',
            field=models.CharField(max_length=55, verbose_name='Пробег автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='SeriaCar',
            field=models.CharField(max_length=55, verbose_name='Серия автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='YearCar',
            field=models.CharField(max_length=55, verbose_name='Год выпуска автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='YourCity',
            field=models.CharField(max_length=55, verbose_name='Город продажи'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='YourMail',
            field=models.CharField(max_length=55, verbose_name='Ваша почта'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='YourName',
            field=models.CharField(max_length=55, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='advertisecar',
            name='YourPhone',
            field=models.CharField(max_length=55, verbose_name='Ваш телефон'),
        ),
    ]
