# Generated by Django 2.2.7 on 2020-01-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0005_remove_advertisecomments_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisecomments',
            name='ID_Advertisement',
            field=models.CharField(max_length=30, verbose_name='Номер комментария'),
        ),
    ]
