# Generated by Django 2.2.7 on 2020-01-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0006_auto_20200111_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisecar',
            name='ComfortCar',
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='ComfortCar1',
            field=models.CharField(default=None, max_length=55, verbose_name='Комфорт1 автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='ComfortCar2',
            field=models.CharField(default=None, max_length=55, verbose_name='Комфорт2 автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='ComfortCar3',
            field=models.CharField(default=None, max_length=55, verbose_name='Комфорт3 автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='MediaAudioSystemCar',
            field=models.CharField(default=None, max_length=55, verbose_name='Мультмедиааудиосистемы автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='MediaSystemCar',
            field=models.CharField(default=None, max_length=55, verbose_name='Мультмедиасистемы автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='SecurityCar1',
            field=models.CharField(default=None, max_length=55, verbose_name='Безопасность1 автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='SecurityCar2',
            field=models.CharField(default=None, max_length=55, verbose_name='Безопасность2 автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='SecurityCar3',
            field=models.CharField(default=None, max_length=55, verbose_name='Безопасность3 автомобиля'),
            preserve_default=False,
        ),
    ]
