# Generated by Django 2.2.7 on 2020-02-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0006_auto_20200129_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisecomments',
            name='Email',
            field=models.CharField(max_length=30, verbose_name='Емейл пользователя'),
        ),
    ]
