# Generated by Django 2.2.7 on 2020-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0009_auto_20200206_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='ID_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='cover_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='electro_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='exterer_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='gearbox_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='hod_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='kuzov_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='motor_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='salon_average',
            field=models.CharField(default=None, max_length=30, verbose_name='Целостность кузова (среднее)'),
            preserve_default=False,
        ),
    ]
