# Generated by Django 2.2.7 on 2020-01-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0009_auto_20200114_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisecar',
            name='AdvId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='motor.User'),
            preserve_default=False,
        ),
    ]
