# Generated by Django 2.2.7 on 2020-01-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0010_advertisecar_advid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisecar',
            name='AdvId',
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='UserId',
            field=models.ForeignKey(help_text='Каким пользователем создано объявление', null=True, on_delete=django.db.models.deletion.CASCADE, to='motor.User', verbose_name='Номер пользователя'),
        ),
    ]
