# Generated by Django 2.2.7 on 2020-01-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0011_auto_20200114_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisecar',
            name='UserId',
        ),
    ]
