# Generated by Django 2.2.7 on 2020-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0011_remove_ratings_id_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Advertisement', models.CharField(max_length=30, verbose_name='Номер объявления')),
                ('ID_User', models.CharField(max_length=30, verbose_name='Номер пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_LIST', models.CharField(max_length=30, verbose_name='Номер списка сравнения')),
            ],
        ),
    ]
