# Generated by Django 2.2.7 on 2020-01-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0013_advertisecar_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisecar',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
