# Generated by Django 2.2.7 on 2020-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0013_auto_20200219_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisecar',
            name='ChangeCar',
            field=models.CharField(default=None, max_length=55, verbose_name='Нужна ли растаможка?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='CustomCar',
            field=models.CharField(default=None, max_length=55, verbose_name='Нужна ли растаможка?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='PasswordCar',
            field=models.CharField(default=None, max_length=55, verbose_name='ПТС'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='RemontCar',
            field=models.CharField(default=None, max_length=55, verbose_name='Нужен ли ремонт?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisecar',
            name='WheelCar',
            field=models.CharField(default=None, max_length=55, verbose_name='Расположение руля'),
            preserve_default=False,
        ),
    ]
