# Generated by Django 2.2.7 on 2020-01-17 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0014_auto_20200117_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisecar',
            name='ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='motor.User'),
            preserve_default=False,
        ),
    ]
