# Generated by Django 2.2.7 on 2020-02-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0014_auto_20200220_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisongeneral',
            name='ID_LIST',
            field=models.ImageField(max_length=30, upload_to='', verbose_name='Список сравнения объявлений'),
        ),
    ]
