# Generated by Django 2.2.7 on 2020-02-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0015_auto_20200221_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisongeneral',
            name='ID_LIST',
            field=models.IntegerField(verbose_name='Список сравнения объявлений'),
        ),
    ]
