# Generated by Django 2.2.7 on 2020-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0016_auto_20200221_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisongeneral',
            name='ID_LIST',
            field=models.CharField(max_length=30, verbose_name='Список сравнения объявлений'),
        ),
    ]
