# Generated by Django 2.1.2 on 2018-12-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=30)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('Phone', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('CreatedDate', models.DateTimeField()),
                ('ModifiedDate', models.DateTimeField()),
                ('Active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
