# Generated by Django 2.1.2 on 2018-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_auto_20181211_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Active',
            field=models.BooleanField(verbose_name='Статус пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ModifiedDate',
            field=models.DateTimeField(verbose_name='Дата последнего изменения'),
        ),
    ]
