# Generated by Django 2.1.2 on 2018-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_auto_20181211_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.AlterField(
            model_name='user',
            name='Active',
            field=models.BooleanField(help_text='Активен / Не активен', verbose_name='Статус пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CreatedDate',
            field=models.DateTimeField(help_text='День, когда был создан аккаунт', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ModifiedDate',
            field=models.DateTimeField(help_text='Когда было изменено что-нибудь в аккаунте', verbose_name='Дата последнего изменения'),
        ),
    ]
