# Generated by Django 2.1.2 on 2018-12-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0004_auto_20181211_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupType', models.CharField(choices=[('Adm', 'Администраторы'), ('Usr', 'Пользователи')], default='Пользователи', max_length=15, verbose_name='Группа пользователя')),
                ('Active', models.BooleanField(help_text='Активена / Не активена', verbose_name='Статус группы')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='GroupID',
            field=models.ForeignKey(default=1, help_text='К какой группе относится пользователь', on_delete=django.db.models.deletion.CASCADE, to='motor.UserGroup', verbose_name='Группа пользователя'),
            preserve_default=False,
        ),
    ]
