# Generated by Django 2.1.2 on 2018-12-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0005_auto_20181211_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name_plural': 'Пользовательские группы'},
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='GroupType',
            field=models.CharField(choices=[('Администраторы', 'Администраторы'), ('Пользователи', 'Пользователи')], default='Пользователи', max_length=15, verbose_name='Группа пользователя'),
        ),
    ]
