# Generated by Django 2.1.2 on 2018-12-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0006_auto_20181211_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='GroupID',
            field=models.ForeignKey(help_text='К какой группе относится пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to='motor.UserGroup', verbose_name='Группа пользователя'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='GroupType',
            field=models.CharField(max_length=15, verbose_name='Группа пользователя'),
        ),
    ]
