# Generated by Django 2.1.2 on 2018-12-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0007_auto_20181211_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default=True, max_length=30, verbose_name='Пароль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Active',
            field=models.BooleanField(default=True, help_text='Активен / Не активен', verbose_name='Статус пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, help_text='День, когда был создан аккаунт', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ModifiedDate',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда было изменено что-нибудь в аккаунте', verbose_name='Дата последнего изменения'),
        ),
    ]
