# Generated by Django 2.1.2 on 2018-12-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0008_auto_20181226_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(default='None', max_length=30, verbose_name='Пароль пользователя'),
        ),
    ]
