# Generated by Django 2.2.7 on 2019-11-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0009_auto_20181226_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=30, unique=True, verbose_name='Емейл пользователя'),
        ),
    ]
