language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - flake8 . --ignore=F841,W503,E126,E123,E501,E127,47,335,334,333,321,841
deploy:
  provider: heroku
  api_key: "28cfa6e0-d617-47c0-b1be-1ce9632b3d71"
  app: motor-project